// src/lib/projects.js

export const projects = [
  {
    slug: "hr-management-platform",
    title: "HR Management Platform",
    tag: "Enterprise SaaS",
    desc: "A unified HR work progress and task assigning platform handling employee performance and analytics in one operating layer.",
    stack: ["React", "Fast API", "SQL", "AWS"],
    color: "from-[#00B4D8] to-[#0F4C81]",
    liveUrl: "https://www.workday.com",
    challenge: "Many organizations relied on manual processes and multiple disconnected systems to manage employee records, attendance, payroll, leave, and performance. This resulted in data duplication, reduced productivity, delayed HR operations, and limited reporting capabilities.",
    solution: "We developed a centralized HR Management System that automates the complete employee lifecycle. The platform provides employee onboarding, attendance management, leave tracking, payroll processing, performance evaluation, role-based dashboards, and real-time analytics, enabling HR teams to work more efficiently.",
    features: [
      "Employee Profile Management",
      "Attendance & Shift Tracking",
      "Leave & Holiday Management",
      "Payroll Processing",
      "Performance & Appraisal System",
      "Role-Based Access Control",
      "Reports & Analytics Dashboard",
      "Employee Self-Service Portal",
    ],
    results: [
      { num: "100%", label: "Digital HR Process" },
      { num: "10K+", label: "Employees Managed" },
      { num: "40%", label: "Faster Work Progress" },
    ],
    gallery: [
      { src: "/Hr_solutions_jaitra/1.png", caption: "Team dashboard" },
      { src: "/Hr_solutions_jaitra/2.png", caption: "Performance review" },
      { src: "/Hr_solutions_jaitra/3.png", caption: "People analytics" },
      { src: "/Hr_solutions_jaitra/4.png", caption: "Payroll engine" },
      { src: "/Hr_solutions_jaitra/5.png", caption: "Org planning" },
      { src: "/Hr_solutions_jaitra/6.png", caption: "Onboarding flow" },
    ],
  },
  {
    slug: "news-application",
    title: "News Application",
    tag: "Media & Publishing",
    desc: "A well-optimized user experience news application where the algorithm interacts intuitively irrespective of user age group.",
    stack: ["Next.js", "Python", "Redis", "GCP"],
    color: "from-[#0F4C81] to-[#00B4D8]",
    liveUrl: "https://www.hackerrank.com",
    challenge: "Users needed a fast and reliable platform to access real-time news from multiple categories in a single application without dealing with cluttered UI or slow loading times.",
    solution: "Developed a responsive News App with live news feeds, category-based browsing, search functionality, and real-time API integration for an improved and personalized reading experience.",
    features: [
      "Real-Time News Feed",
      "Category-Based Articles",
      "Trending News Section",
      "Advanced Search & Filters",
      "Bookmark Favorite Articles",
      "Responsive Mobile Design",
      "Breaking News Push Updates",
      "Fast API Integration",
    ],
    results: [
      { num: "1000+", label: "News Articles Daily" },
      { num: "120k+", label: "Active Users" },
      { num: "Real-Time", label: "Live Updates" },
    ],
    gallery: [
      { src: "/news-application/1.png", caption: "Assessment console" },
      { src: "/news-application/2.png", caption: "Candidate cohort" },
      { src: "/news-application/3.png", caption: "Live coding round" },
      { src: "/news-application/4.png", caption: "Campus drive" },
      { src: "/news-application/5.png", caption: "Adaptive engine" },
      { src: "/news-application/6.png", caption: "Recruiter view" },
    ],
  },
  {
    slug: "surgical-world",
    title: "Surgical World",
    tag: "Healthcare E-Commerce",
    desc: "End-to-end ecommerce platform for surgical equipment, patient monitoring devices, and daily life BP instruments.",
    stack: ["Flutter", "Rust", "ZK proofs", "PostgreSQL"],
    color: "from-[#0F4C81] via-[#00B4D8] to-[#0F4C81]",
    liveUrl: "https://www.voatz.com",
    challenge: "Medical suppliers needed an efficient platform to manage products, distributors, inventory, and customer orders while reducing the manual processes that led to fulfillment delays.",
    solution: "Built a secure healthcare platform that centralizes product management, inventory tracking, order processing, distributor management, and customer interactions all in one unified ecosystem.",
    features: [
      "Medical Product Catalog",
      "Advanced Inventory Management",
      "Distributor Management",
      "Customer Order Tracking",
      "Secure Biometric Authentication",
      "Product Search & Filtering",
      "Responsive Admin Dashboard",
      "Order Reports & Analytics",
    ],
    results: [
      { num: "500+", label: "Medical Products" },
      { num: "99.999%", label: "System Integrity" },
      { num: "24/7", label: "Customer Support" },
    ],
    gallery: [
      { src: "/surgical_World/1.png", caption: "Product catalog" },
      { src: "/surgical_World/2.png", caption: "Product details" },
      { src: "/surgical_World/3.png", caption: "Cart & checkout" },
      { src: "/surgical_World/4.png", caption: "Order tracking" },
      { src: "/surgical_World/5.png", caption: "Biometric auth" },
      { src: "/surgical_World/6.png", caption: "Admin dashboard" },
    ],
  },
  {
    slug: "youtube-analytics",
    title: "YouTube Analytics Platform",
    tag: "Analytics · ERP",
    desc: "Real-time YouTube analytics platform to assess trending channels in your domain, competitor analysis with rich graphs, and high-level insights.",
    stack: ["SAP CPI", "Java", "Kafka", "React"],
    color: "from-[#00B4D8] to-[#0F4C81]",
    liveUrl: "https://www.sap.com",
    challenge: "Media agencies and creators struggled to consolidate data across multiple YouTube channels, making competitor analysis and trend forecasting a highly manual, error-prone process.",
    solution: "Engineered a robust, real-time analytics ERP integrating direct YouTube APIs with SAP CPI and Kafka to deliver automated insights, predictive trends, and seamless financial reporting.",
    features: [
      "Real-Time Competitor Tracking",
      "Audience Sentiment & Comment Analysis",
      "Automated SAP Integration",
      "Custom Report Generation",
      "Engagement Metrics Dashboards",
      "Trend Forecasting Engine",
      "Multi-channel Aggregation",
    ],
    results: [
      { num: "$3.2M", label: "Saved Annually" },
      { num: "10x", label: "Faster Reporting" },
      { num: "100%", label: "Data Accuracy" },
    ],
    gallery: [
      { src: "/youtube-analtyics/1.png", caption: "Dashboard overview" },
      { src: "/youtube-analtyics/2.png", caption: "Channel comparison" },
      { src: "/youtube-analtyics/3.png", caption: "Trending analysis" },
      { src: "/youtube-analtyics/4.png", caption: "Audience insights" },
      { src: "/youtube-analtyics/5.png", caption: "Engagement metrics" },
      { src: "/youtube-analtyics/6.png", caption: "Report generator" },
    ],
  },
];

export const getProject = (slug) => projects.find((p) => p.slug === slug);